default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['host_postgres'] %>
  port: <%= ENV['port_postgres'] %>
  username: <%= ENV['username_postgres'] %>
  password: <%= ENV['password_postgres'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: registros_development

test:
  <<: *default
  database: registros_test

production:
  <<: *default
  database: registros_production
  username: registros
  password: <%= ENV['REGISTROS_DATABASE_PASSWORD'] %>
